name: Production Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: echo "Deploying to Production"
        
      - name: Show system info
        run: uname -a
